yarnPath: .yarn/releases/yarn-3.6.2.cjs
nodeLinker: pnp
# nodeLinker: node-modules

# packageExtensions:
#   "@craco/craco@*":
#     peerDependencies:
#       postcss: "*"
      
#   "eslint-config-react-app@*":
#     peerDependencies:
#       "@babel/plugin-syntax-flow": "*"
#       "@babel/plugin-transform-react-jsx": "*"

# # Peer dependency 경고 무시 설정
# peerDependencyRules:
#   ignoreMissing:
#     - "@firebase/app"
#     - "@firebase/app-types"
#     - "@types/node"
#     - typescript
#     - postcss
#     - "@babel/plugin-syntax-flow"
#     - "@babel/plugin-transform-react-jsx"